/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Cat Facts API
 * API для получения фактов о кошках с пагинацией
 * OpenAPI spec version: 1.0.0
 */

export type GetFactsParams = {
/**
 * Номер страницы
 */
page?: number;
};
