/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Cat Facts API
 * API для получения фактов о кошках с пагинацией
 * OpenAPI spec version: 1.0.0
 */
import type { Fact } from './fact';
import type { PaginatedFactsLinksItem } from './paginatedFactsLinksItem';

export interface PaginatedFacts {
  current_page?: number;
  data?: Fact[];
  first_page_url?: string;
  last_page_url?: string;
  links?: PaginatedFactsLinksItem[];
  /** @nullable */
  next_page_url?: string | null;
  /** @nullable */
  prev_page_url?: string | null;
  from?: number;
  to?: number;
  per_page?: number;
  total?: number;
}
